apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchsa
  annotations:
    image.openshift.io/triggers: |
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "cli:latest",
            "namespace": "openshift"
          },
          "fieldPath": "spec.template.spec.containers[?(@.name==\"watchsa\")].image"
        }
      ]
spec:
  replicas: 1
  selector: 
    matchLabels:
      opendatahub.io/odh-managed: "true"
  template:
    metadata:
      labels:
        opendatahub.io/odh-managed: "true"
    spec:
      serviceAccountName: watchsa
      containers:
        - image: cli
          name: watchsa
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /bin/bash
            - /scripts/watchsa.sh
          volumeMounts:
            - name: watchsa
              mountPath: /scripts
      volumes:
        - name: watchsa
          configMap:
            name: watchsa
